description = "Ubuntu 22.04 Jammy Jellyfish full image with buildpacks for Apache HTTPD, Go, Java, Java Native Image, .NET, NGINX, Node.js, PHP, Procfile, Python, and Ruby"

[build]
  image = "docker.io/paketobuildpacks/build-jammy-full:0.1.222"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/dotnet-core:3.1.81"
  version = "3.1.81"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/go:4.13.91"
  version = "4.13.91"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/java-native-image:11.15.88"
  version = "11.15.88"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/java:18.12.138"
  version = "18.12.138"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/nodejs:9.3.74"
  version = "9.3.74"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/php:2.19.80"
  version = "2.19.80"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/procfile:5.15.0"
  version = "5.15.0"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/python:2.30.69"
  version = "2.30.69"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/ruby:0.47.83"
  version = "0.47.83"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/web-servers:4.12.0"
  version = "4.12.0"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/deno:0.6.0"
  version = "0.6.0"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/runway:0.1.74"
  version = "0.1.74"

[lifecycle]
  version = "0.21.20"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/ruby"
    version = "0.47.83"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/dotnet-core"
    version = "3.1.81"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/go"
    version = "4.13.91"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/python"
    version = "2.30.69"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/php"
    version = "2.19.80"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/runway"
    version = "0.1.74"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/web-servers"
    version = "4.12.0"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/java-native-image"
    version = "11.15.88"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/java"
    version = "18.12.138"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/nodejs"
    version = "9.3.74"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.15.0"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/deno"
    version = "0.6.0"

[run]

  [[run.images]]
    image = "r.planetary-quantum.com/runway-public/jammy/run:latest"

[stack]
  id = "io.buildpacks.stacks.jammy"
