description = "Ubuntu 24.04 Noble Numbat base image with buildpacks"

[build]
  image = "docker.io/paketobuildpacks/ubuntu-noble-build:0.0.122"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/dotnet-core:3.1.77"
  version = "3.1.77"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/go:4.13.87"
  version = "4.13.87"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/java-native-image:11.15.85"
  version = "11.15.85"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/java:18.12.134"
  version = "18.12.134"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/nodejs:9.3.70"
  version = "9.3.70"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/php:2.19.76"
  version = "2.19.76"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/procfile:5.13.7"
  version = "5.13.7"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/python:2.30.65"
  version = "2.30.65"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/ruby:0.47.79"
  version = "0.47.79"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/web-servers:4.10.0"
  version = "4.10.0"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/deno:0.6.0"
  version = "0.6.0"

[[buildpacks]]
  uri = "docker://r.planetary-quantum.com/buildpacks/runway:0.1.71"
  version = "0.1.71"

[lifecycle]
  version = "0.21.18"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/ruby"
    version = "0.47.79"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/dotnet-core"
    version = "3.1.77"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/go"
    version = "4.13.87"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/python"
    version = "2.30.65"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/php"
    version = "2.19.76"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/runway"
    version = "0.1.71"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/web-servers"
    version = "4.10.0"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/java-native-image"
    version = "11.15.85"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/java"
    version = "18.12.134"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/nodejs"
    version = "9.3.70"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.13.7"

[[order]]

  [[order.group]]
    id = "runway-buildpacks/deno"
    version = "0.6.0"

[run]

  [[run.images]]
    image = "r.planetary-quantum.com/runway-public/noble/run:latest"

[stack]
  id = "io.buildpacks.stacks.noble"
