FROM paketobuildpacks/ubuntu-noble-run:0.0.77

# adding a default port because that makes everything work better with runway
# see https://github.com/pngmbh/issues/issues/1201#issuecomment-1191657548
ENV PORT=5000
EXPOSE 5000