# https://github.com/paketo-buildpacks/jammy-full-stack/releases
FROM paketobuildpacks/run-jammy-full:0.1.85

# adding a default port because that makes everything work better with runway
# see https://github.com/pngmbh/issues/issues/1201#issuecomment-1191657548
ENV PORT=5000
EXPOSE 5000
