api = "0.8"

[buildpack]
  description = "A language family buildpack for pulling in all buildpacks related to building .NET Core apps"
  homepage = "https://www.runway.horse/docs/recipes/deploy-dotnet/"
  id = "runway-buildpacks/dotnet-core"
  keywords = ["dotnet"]
  name = "Paketo Buildpack for .NET Core"
  version = "3.1.16"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dotnet-core/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core-sdk"
    optional = true
    version = "1.0.21"

  [[order.group]]
    id = "paketo-buildpacks/icu"
    optional = true
    version = "0.7.48"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "7.8.1"

  [[order.group]]
    id = "paketo-buildpacks/dotnet-publish"
    optional = true
    version = "1.0.13"

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core-aspnet-runtime"
    optional = true
    version = "1.0.24"

  [[order.group]]
    id = "paketo-buildpacks/dotnet-execute"
    version = "1.0.17"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.11.3"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.9.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.10.2"
