name: go-generate

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * 1"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: warjiang/setup-skopeo@v0.1.3
      - run: |
          skopeo login \
          --username ${{ secrets.QUANTUM_REGISTRY_USERNAME }} \
          --password ${{ secrets.QUANTUM_REGISTRY_PASSWORD }} \
          r.planetary-quantum.com
      - uses: updatecli/updatecli-action@v2
      - env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          updatecli \
            apply \
            -c .github/update-cli/go-generate.yml \
            -v .github/update-cli/values.yml