name: PR

on:
  pull_request:

jobs:
  push:
    name: Push
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v5

    - name: Install Global Pack
      uses: buildpacks/github-actions/setup-pack@main
      with:
        pack-version: 0.35.1

    - name: Build run-image
      uses: docker/build-push-action@v6
      with:
        context: runimage
        cache-from: r.planetary-quantum.com/runway-public/runway-runimage:jammy-full
        push: false
        tags: runimage-test

    - name: Create Builder Image
      run: |
        make build-builder

    - shell: bash
      run: |
        LAYER_COUNT=$(docker image inspect builder | jq '.[].RootFS.Layers | length')
        if [ "$LAYER_COUNT" -gt "100" ]; then
          echo "Too many layers: $LAYER_COUNT (limit: 100)"
          exit 1
        fi