name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  push:
    name: Push
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v5
    - uses: buildpacks/github-actions/setup-pack@main
      with:
        pack-version: 0.38.2

    - uses: docker/login-action@v3
      with:
        registry: r.planetary-quantum.com
        username: ${{ secrets.QUANTUM_REGISTRY_USERNAME }}
        password: ${{ secrets.QUANTUM_REGISTRY_PASSWORD }}
    - uses: docker/setup-buildx-action@v3

    - id: meta-run
      uses: docker/metadata-action@v5
      with:
        images: |
          r.planetary-quantum.com/runway-public/runway-runimage
        tags: |
          type=semver,prefix=jammy-full-,pattern={{version}}
          type=raw,value=jammy-full

    - id: meta-builder
      uses: docker/metadata-action@v5
      with:
        images: |
          r.planetary-quantum.com/runway-public/runway-buildpack-stack
        tags: |
          type=semver,prefix=jammy-full-,pattern={{version}}
          type=raw,value=jammy-full

    - uses: docker/build-push-action@v6
      with:
        context: runimage
        cache-from: r.planetary-quantum.com/runway-public/runway-runimage:jammy-full
        push: true
        tags: ${{ steps.meta-run.outputs.tags }}
        labels: ${{ steps.meta-run.outputs.labels }}

    - name: Create Builder Unflattened
      run: make build-builder-unflattened

    - run: |
        echo "## Duplicate Analysis" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        ./scripts/builder-analyzer --builder-name builder-unflattened duplicates >> $GITHUB_STEP_SUMMARY || echo "No duplicates found" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Buildpacks to Flatten" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        ./scripts/builder-analyzer --builder-name builder-unflattened flatten --pretty >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

    - name: Create Builder Image
      run: make build-builder

    - name: Push builder
      run: |
        echo "${{ steps.meta-builder.outputs.tags }}" | while read -r tag; do
          docker tag runway-builder "$tag"
          docker push "$tag"
        done

    - uses: softprops/action-gh-release@v2
