name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  push:
    name: Push
    runs-on: ubuntu-22.04
    steps:

    - name: Parse Event
      id: event
      run: |
        echo "tag=$(jq -r '.release.tag_name' "${GITHUB_EVENT_PATH}" | sed s/^v//)" >> "$GITHUB_OUTPUT"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Get pack version
      id: pack-version
      run: |
        version=$(jq -r .pack "scripts/.util/tools.json")
        echo "version=${version#v}" >> "$GITHUB_OUTPUT"

    - name: Install Global Pack
      uses: buildpacks/github-actions/setup-pack@main
      with:
        pack-version: ${{ steps.pack-version.outputs.version }}

    - name: Enable Experimental Pack Features
      run: |
        if [ -f "scripts/options.json" ] && jq -e -r .pack_config_enable_experimental "scripts/options.json" > /dev/null; then
          pack config experimental true
        fi

    - name: Create Builder Image
      run: |
        pack builder create builder --config builder.toml

    - name: Docker login
      uses: docker/login-action@v3
      with:
        registry: r.planetary-quantum.com
        username: ${{ secrets.BUILDPACK_REGISTRY_USERNAME }}
        password: ${{ secrets.BUILDPACK_REGISTRY_PASSWORD }}

    - name: Push To Dockerhub
      env:
        IMG: r.planetary-quantum.com/runway-public/runway-buildpack
      run: |
        docker tag builder "${IMG}:jammy-full"
        docker tag builder "${IMG}:jammy-full-${{ steps.event.outputs.tag }}"
        docker push "${IMG}:jammy-full"
        docker push "${IMG}:jammy-full-${{ steps.event.outputs.tag }}"
