name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  push:
    name: Push
    runs-on: ubuntu-22.04
    steps:

    - name: Parse Event
      id: event
      run: |
        echo "tag=$(jq -r '.release.tag_name' "${GITHUB_EVENT_PATH}" | sed s/^v//)" >> "$GITHUB_OUTPUT"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Global Pack
      uses: buildpacks/github-actions/setup-pack@main
      with:
        pack-version: 0.35.1

    - name: Docker login
      uses: docker/login-action@v3
      with:
        registry: r.planetary-quantum.com
        username: ${{ secrets.QUANTUM_REGISTRY_USERNAME }}
        password: ${{ secrets.QUANTUM_REGISTRY_PASSWORD }}
    - uses: docker/setup-buildx-action@v3

    - id: meta-run
      uses: docker/metadata-action@v5
      with:
        images: |
          r.planetary-quantum.com/runway-public/runway-runimage
        tags: |
          type=semver,prefix=jammy-full-,pattern={{version}}
          type=raw,value=jammy-full

    - name: Build and push run-image
      uses: docker/build-push-action@v6
      with:
        context: runimage
        cache-from: r.planetary-quantum.com/runway-public/runway-runimage:jammy-full
        push: true
        tags: ${{ steps.meta-run.outputs.tags }}

    - name: Create Builder Image
      run: |
        pack builder create builder --config builder.toml

    - name: Push builder
      env:
        IMG: r.planetary-quantum.com/runway-public/runway-buildpack-stack
      run: |
        docker tag builder "${IMG}:jammy-full"
        docker tag builder "${IMG}:jammy-full-${{ steps.event.outputs.tag }}"
        docker push "${IMG}:jammy-full"
        docker push "${IMG}:jammy-full-${{ steps.event.outputs.tag }}"
