name: Update buildpack.toml and Send Pull Request

on:
  schedule:
  - cron: '1 6 * * *' # daily at 06:01 UTC
  workflow_dispatch: {}

concurrency: buildpack_update

jobs:
  update-buildpack-toml:
    name: Update ${{ matrix.buildpack }}/buildpack.toml
    strategy:
      matrix:
        buildpack: [dotnet-core, go, java, java-native-image, nodejs, ruby, runway]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v5

    - id: names
      run: |
        LOCAL_PATH=meta/${{ matrix.buildpack }}
        echo "branch=automation/${{ matrix.buildpack }}/buildpack.toml/update" >> $GITHUB_OUTPUT
        echo "path=${LOCAL_PATH}" >> $GITHUB_OUTPUT
        echo "toml=${LOCAL_PATH}/buildpack.toml" >> $GITHUB_OUTPUT

    - name: increase version in buildpack.toml for ${{ steps.names.outputs.path }}
      run: ./scripts/increase-version.sh ./${{ steps.names.outputs.toml }}

    - uses: paketo-buildpacks/github-config/actions/pull-request/checkout-branch@main
      with:
        branch: ${{ steps.names.outputs.branch }}

    - name: Update buildpack.toml for ${{ steps.names.outputs.path }}
      id: update
      uses: paketo-buildpacks/github-config/actions/buildpack/update@main
      with:
        buildpack_toml_path: ${{ steps.names.outputs.toml }}
        package_toml_path: ${{ steps.names.outputs.path }}/package.toml
        no_cnb_registry: true

    - id: commit
      uses: paketo-buildpacks/github-config/actions/pull-request/create-commit@main
      with:
        message: "chore(deps): update buildpacks in ${{ steps.names.outputs.toml }}"
        pathspec: "."

    - if: ${{ steps.commit.outputs.commit_sha != '' && steps.update.outputs.semver_bump != '<none>'}}
      uses: paketo-buildpacks/github-config/actions/pull-request/push-branch@main
      with:
        branch: ${{ steps.names.outputs.branch }}

    - if: ${{ steps.commit.outputs.commit_sha != '' && steps.update.outputs.semver_bump != '<none>' }}
      uses: paketo-buildpacks/github-config/actions/pull-request/open@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "chore(deps): buildpacks in ${{ steps.names.outputs.toml }}"
        branch: ${{ steps.names.outputs.branch }}
        label: "semver:${{ steps.update.outputs.semver_bump }}"
